server:
  port: 8080
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  profiles: dev
  application:
    name: hap-api-gateway
  cloud:
    config:
      retry:
        maxAttempts: 32
        multiplier: 1.5
        maxInterval: 10000
    stream:
      bindings:
        input:
          destination: eureka-instance
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8100/eureka/}
    registryFetchIntervalSeconds: 10
    disable-delta: true
management:
  port: 8081
  security:
    enabled: false


---


server:
  port: 8080
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  profiles: sit
  application:
    name: hap-api-gateway
  cloud:
    config:
      retry:
        maxAttempts: 32
        multiplier: 1.5
        maxInterval: 10000
    stream:
      bindings:
        input:
          destination: eureka-instance
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8200/eureka/}
    registryFetchIntervalSeconds: 10
    disable-delta: true
management:
  port: 8081
  security:
    enabled: false